apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-account-service
  labels:
    app: bookstore-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-account-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: bookstore-account-service
    spec:
      containers:
      - name: bookstore-account-service
        image: bagesh2050/bookstore-account-service:0.0.2.RELEASE
        #imagePullPolicy: Always
        ports:
        - containerPort: 7001
        env:
        - name: AUTH_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: account-service-config-map
              key: AUTH_SERVER_HOST
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-conf
              key: database
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-conf
              key: host
---    
apiVersion: v1
kind: Service
metadata:
  name: bookstore-account-service-svc
spec:
  #type: NodePort
  selector:
    app: bookstore-account-service
  ports:
  - name: bookstore-account-service
    #protocol: TCP
    port: 7001
    targetPort: 7001
  clusterIP: None
    #nodePort: 30031