server:
  port: 7003
  servlet:
    context-path: /notification
    
    
spring:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: consumer-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      template:
        default-topic: book_order_topic
    mail:
        host: smtp.gmail.com
        username: mail.bagesh@gmail.com
        password: wimjxwnppwuuzkth
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    